server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"

      routes:
        - id: payments-service
          uri: http://payments-service:8081
          predicates:
            - Path=/api/v1/payments/**

        - id: orders-service
          uri: http://orders-service:8082
          predicates:
            - Path=/api/v1/orders/**

        - id: payments-api-docs
          uri: http://payments-service:8081
          predicates:
            - Path=/api/payments/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: orders-api-docs
          uri: http://orders-service:8082
          predicates:
            - Path=/api/orders/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: payments-swagger-ui
          uri: http://payments-service:8081
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/payments/(?<segment>.*), /${segment}

        - id: orders-swagger-ui
          uri: http://orders-service:8082
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /${segment}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Payments Service
        url: payments/v3/api-docs
      - name: Orders Service
        url: orders/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true